# CENTOS-8

- name: download zabbix-agent repository in CentOS8
  get_url:
    url: https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm
    dest: /tmp
    mode: '0440'
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"
  become: true

- name: installing zabbix-agent .rpm in CentOS8
  dnf:
    name: /tmp/zabbix-release-5.4-1.el8.noarch.rpm
    state: latest
    disable_gpg_check: true
    update_cache: yes
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"
  become: true

  # CENTOS-7
- name: download zabbix-agent repository in CentOS8
  get_url:
    url:  https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-release-5.4-1.el7.noarch.rpm
    dest: /tmp
    mode: '0440'
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
  become: true

- name: installing zabbix-agent .rpm in CentOS8
  yum:
    name: /tmp/zabbix-release-5.4-1.el7.noarch.rpm
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
  become: true




  