# UBUNTU-20.04
- name: download zabbix-agent repository in Ubuntu20.04
  get_url:
    url: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu20.04_all.deb
    dest: /tmp
    mode: '0440'
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20"
  become: true

- name: install zabbix-agent .deb in Ubuntu20.04
  apt:
     deb: /tmp/zabbix-release_5.4-1+ubuntu20.04_all.deb
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20"
  become: true
  
- name: ensure zabbix-agent2 installed
  apt:
   update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20"
  become: true

# UBUNTU-18.04
- name: download zabbix-agent repository in Ubuntu18.04
  get_url:
    url: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu18.04_all.deb
    dest: /tmp
    mode: '0440'
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18"
  become: true

- name: install zabbix-agent .deb in Ubuntu18.04
  apt:
     deb: /tmp/zabbix-release_5.4-1+ubuntu18.04_all.deb
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18"
  become: true
  
- name: ensure zabbix-agent2 installed
  apt:
   update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18"
  become: true



