---
- name: Converge
  hosts: all
  tasks:
    - name: "Include cacti"
      include_role:
        name: "cacti"
        
  roles:
    - geerlingguy.pip
    - geerlingguy.git
    # - geerlingguy.docker
    - cacti

