---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    pre_build_image: true

  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
